rails/alpha-blog/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"

  resources :articles
end

rails/alpha-blog/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/alpha-blog/app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

rails/alpha-blog/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

rails/alpha-blog/app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render "new"
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end
end

rails/alpha-blog/app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
  end

  def about
  end
end

rails/alpha-blog/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

rails/alpha-blog/app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

rails/alpha-blog/app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit  %>
  </p>
<% end %>

<p><%= link_to "Cancel and return to articles listing", articles_path %></p>

rails/alpha-blog/app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>

rails/alpha-blog/app/views/articles/index.html.erb
<h1>Article listing page</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan=3>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article|  %>
        <tr>
            <td><%= article.title %></td>
            <td><%= article.description %></td>
            <td><%= link_to "Show", article_path(article) %></td>
            <td><%= link_to "Edit", edit_article_path(article) %></td>
            <td><%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<p><%= link_to "Create new article", new_article_path %></p>

rails/alpha-blog/app/views/articles/new.html.erb
<h1>Create a new Article</h1>
<%= render 'form' %>

rails/alpha-blog/app/views/articles/show.html.erb
<h1>Showing Article Details</h1>

<p><strong>Title: </strong><%= @article.title  %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<p>
  <%= link_to "Edit", edit_article_path(@article) %> |
  <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %> |
  <%= link_to "Return to articles listing", articles_path %>
</p>

rails/alpha-blog/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %> 
  <%= msg %> 
<% end %>

rails/alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

rails/alpha-blog/app/views/pages/about.html.erb
<h1>This is the About page</h1>

<p>
  <%= link_to "Articles listing", articles_path %> |
  <%= link_to "Home Page", root_path %>
</p>

rails/alpha-blog/app/views/pages/home.html.erb
<h1>This is the Home page</h1>

<p>
  <%= link_to "Articles listing", articles_path %> |
  <%= link_to "About", about_path %>
</p>